### ISSUE TITLE
First Code Review

### ISSUE THREAD

**Issue by mahmoudyusof** [salma77/cracking-the-coding-interview#1]
# Chapter 1
## Great
- Good naming and clear docstrings
- Modular code and good separation of helper functions

## Can be better
- docstring for helper functions is absent
- in `ArraysAndStrings::CompressString` line 13 docstring parameter name doesn't match actual parameter name

# Chapter 2
## Great
- Good encapsulation of data in data structure
- Good naming of classes, functions and directories
- Clear docstrings

## Can be better
- naming of nodes can be better `node_1` for example instead of `n1` *7antafa*

# Chapter 3
## Great
- Good encapsulation of data in DataStructure
- Using templates for types in stacks and queues
- Inheritance where needed <3

## Can be better
- main function not needed in `StacksAndQueues`
- Testing for AnimalShelter
- function naming for queue could be more clear, since `add` and `remove` are quite vague, `enqueue` and `dequeue` might be better *more 7antafa*

# Chapter 4
## Great
- Encapsulation and single responsibility
- Great docstrings

## Can be better
- Naming
    - single character variables like `x` and `g`
    - similar names for classes `Graph` and `Graph2`
    - when I saw minBST I thought it was a heap for a minute :'D, maybe `minHeightBST` would be better
- Manual Testing
    - testGetDepthList
    - testGraph
> **NOTE:** if you want to do manual testing, that's fine, however, don't use the `@Test` decorator or even better, just `assertTrue(true)` at the end of the test.

**Comment by salma77** [comment]
I've finished all of these, would you check if we can close this issue?

**Comment by mahmoudyusof** [comment]
Great job
